export enum AuditAction {
  CREATE = 'CREAR',
  AUTHORIZE = 'AUTORIZAR',
  SIGN = 'FIRMAR',
  RECONCILE_STAGING = 'CONCILIAR_STAGING',
  GENERATE_DOCS = 'GENERAR_DOCS',
  REVOKE = 'REVOCAR',
  UPDATE = 'ACTUALIZAR',
  DELETE = 'ELIMINAR',
  RECOVER = 'RECUPERAR',
}
